#!/bin/bash

## This file replaces the Dyalog mapl script
echo " _______     __      _      ____   _____ "
echo "|  __ \ \   / //\   | |    / __ \ / ____|"
echo "|_|  | \ \_/ //  \  | |   | |  | | |     "
echo "     | |\   // /\ \ | |   | |  | | |   _ "
echo " ____| | | |/ /  \ \| |___| |__| | |__| |"
echo "|_____/  |_/_/    \_\______\____/ \_____|"
echo ""
echo "https://www.dyalog.com"
echo ""
echo "*************************************************************************************"
echo "*               This software is for non-commercial evaluation ONLY                 *"
echo "* https://www.dyalog.com/uploads/documents/Private_Personal_Educational_Licence.pdf *"
echo "*************************************************************************************"
echo ""

jupyter notebook --no-browser --ip 0.0.0.0 --port 8888 --allow-root /app/Arrays.ipynb
