#!/bin/bash

pname=`basename $0`

if [ $# = 0 ]; then echo "Usage: $pname directory  [httpport] [rideport]" >& 2 ; exit 128 ; fi
if [ ! -d $1 ]; then echo "$pname: \"$1\" does not exist" >&2 ; exit 1; fi

folder=`readlink -e $1`
httpport="${2:-8080}"
if [ -z $3 ] ; then rideport="" ; else rideport="-p $3:4502 "; fi

( sleep 3 ; firefox http://localhost:$httpport 2>/dev/null ) &

docker run $rideport -p $httpport:8080 -it -v $folder:/app dyalog/miserver:dbg

e=$?
if [ $e != 0 ] ; then echo "$pname: docker returned error code $e" ; exit 1; fi
