#!/bin/bash

pname=`basename $0`

if [ $# != 1 ]; then echo "Usage: $pname directory [rideport]" >& 2 ; exit 128 ; fi
if [ ! -d $1 ]; then echo "$pname: \"$1\" does not exist" >&2 ; exit 1; fi

folder=`readlink -e $1`
rideport="${2:-4502}"

( sleep 3 ; firefox http://localhost:$rideport 2>/dev/null ) &

docker run -p $rideport:4502 -it -v $folder:/app dyalog/dyalog:17.1-dbg

e=$?
if [ $e != 0 ] ; then echo "$pname: docker returned error code $e" ; exit 1; fi
